-d /home/fayz/Documents/hdmi_/impl/gwsynthesis/hdmi_.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/fayz/Documents/hdmi_/src/hdmi_.cst
-cfg /home/fayz/Documents/hdmi_/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
