-d /home/muddassir/Gowin/IDE/bin/FPGA_Projects/moving_block/impl/gwsynthesis/moving_block.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/muddassir/Gowin/IDE/bin/FPGA_Projects/moving_block/src/moving_block.cst
-cfg /home/muddassir/Gowin/IDE/bin/FPGA_Projects/moving_block/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
